//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Observatorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Eventos
    {
        public int ID_Evento { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string Fecha { get; set; }
        public string URL { get; set; }
        public int ID_pais { get; set; }
        public string Hora { get; set; }
    
        public virtual Pais Pais { get; set; }
    }
}
