//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Observatorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Investigacion
    {
        public int ID_inv { get; set; }
        public string Nombre { get; set; }
        public string Autor { get; set; }
        public string Descripcion { get; set; }
        public int ID_tinv { get; set; }
        public int ID_pais { get; set; }
        public int ID_idioma { get; set; }
        public string URL { get; set; }
        public Nullable<System.DateTime> Fecha_publicacion { get; set; }
    
        public virtual Idioma Idioma { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual Tipo_Investigacion Tipo_Investigacion { get; set; }
    }
}
