//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Observatorio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analisis
    {
        public int ID_Analisis { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int ID_TAnalisis { get; set; }
        public int ID_Idioma { get; set; }
        public int ID_Pais { get; set; }
        public string URL { get; set; }
    
        public virtual Idioma Idioma { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual Tipo_Analisis Tipo_Analisis { get; set; }
    }
}
